application: dinamalarnewsapp
version: 5
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /dinamalarnewsapp\.appcache
  static_files: dinamalarnewsapp.appcache
  mime_type: text/cache-manifest
  upload: dinamalarnewsapp\.appcache
  expiration: "0s"

- url: /.*
  script: dinamalarnewsapp.py
