application: dinamalarnewsapp
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: dinamalarnewsapp.py
